import type { FailureType } from "../failures/types.js";

export type BundleEvidenceSummary = {
  evidence_session_id: string;
  evidence_profile: string | null;
  requested_count: number;
  completed_count: number;
  bundle_landed_count: number;
  bundle_failed_count: number;
  bundle_invalid_count: number;
  bundle_timed_out_count: number;
  signature_finalized_count: number;
  signature_not_observed_count: number;
  all_bundle_signatures_finalized_count: number;
  tip_signature_finalized_count: number;
  code_inconsistent_count: number;
  operational_ambiguity_count: number;
  landed_count: number;
  failed_count: number;
  timed_out_count: number;
  inconsistent_count: number;
  finalized_signature_count: number;
  landed_bundle_count: number;
  invalid_bundle_count: number;
  average_submitted_to_processed_ms: number | null;
  average_submitted_to_confirmed_ms: number | null;
  average_submitted_to_finalized_ms: number | null;
  tip_lamports_min: number | null;
  tip_lamports_max: number | null;
  bundle_ids: string[];
  signatures: string[];
  failures_by_type: Partial<Record<FailureType, number>>;
  started_at: string;
  finished_at: string;
  notes: string[];
};

export type BundleEvidenceAuditRow = {
  run_id: string;
  evidence_session_id: string | null;
  bundle_id: string | null;
  signature: string;
  submission_path: string | null;
  rpc_rebroadcast: boolean | null;
  final_bundle_status: string | null;
  landed_slot: number | null;
  timed_out: boolean;
  lifecycle_processed: boolean;
  lifecycle_confirmed: boolean;
  lifecycle_finalized: boolean;
  all_bundle_signatures_finalized: boolean | null;
  tip_signature_finalized: boolean | null;
  transaction_lifecycle_count: number;
  submitted_to_finalized_ms: number | null;
  failure_type: FailureType | null;
  failure_message: string | null;
  bundle_landed: boolean;
  bundle_failed: boolean;
  signature_finalized: boolean;
  code_inconsistent: boolean;
  operational_ambiguity: boolean;
  classification_note: string | null;
  should_count_as_landed: boolean;
  should_count_as_failed: boolean;
  missing_submission_metadata: boolean;
  inconsistent: boolean;
  inconsistency_reason: string | null;
};
